### ISSUE TITLE
「issueベースの開発」 レビュー依頼

### ISSUE THREAD

**Issue by tanariho** [tanariho/graduation_exam#28]
「issueベースの開発」 レビュー依頼を提出いたします。ご確認よろしくお願いいたします！
先ほどのレビュー依頼でURLが間違っておりました、大変申し訳ありません🙇‍♀️

### MVP

- [ ] 新規会員登録
- [ ] ログイン・ログアウト
- [ ] ヨガポーズ図鑑(図鑑のポーズを集める)
- [ ] ヨガ検定
- [ ] ヨガタイマー 
- [ ] Xシェア

## 必要なページ

- [ ] トップページ
- [ ] 新規会員登録画面
- [ ] ログイン画面
- [ ] ログアウト画面
- [ ] マイページ
- [ ] マイページ編集
- [ ] ヨガ検定画面
- [ ] ヨガタイマー画面
- [ ] ヨガポーズ付与画面
- [ ] お試しメニュー画面
- [ ] ヨガ図鑑一覧画面

**Comment by beppumasaki** [comment]
いいと思います！LGTMです！

**Comment by tanariho** [comment]
別府講師
ご確認ありがとうございます！！！
